import os
import django
import random
from decimal import Decimal

# Setup Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'FarmManagementSystem.settings') # Replace if different
django.setup()

from homepage.models import Eggs_production
from django.contrib.auth.models import User

def generate_data():
    # Ensure there's a user
    user = User.objects.first()
    if not user:
        user = User.objects.create_user(username='admin', password='password')

    years = [2024, 2025, 2026]
    
    # Delete existing to prevent duplication if script is run multiple times
    Eggs_production.objects.all().delete()

    records_to_create = []

    for year in years:
        for month in range(1, 13):
            if year == 2026 and month > 3:
                continue

            days_to_gen = list(range(1, 15))  # Minimum 10 data, 14 days
            
            # Make sure we hit the present day (2026-03-23)
            if year == 2026 and month == 3:
                days_to_gen.append(23)
                
            for day in set(days_to_gen):
                record = Eggs_production(
                    user=user,
                    Year=year,
                    Month=month,
                    Day=day,
                    Poultry_number=random.randint(100, 500),
                    Morning_egg_collection=random.randint(50, 200),
                    Midday_egg_collection=random.randint(30, 150),
                    Evening_egg_collection=random.randint(40, 180),
                    Total_egg_collection=0, # Calculated in save
                    Morning_feeds=Decimal(round(random.uniform(5.0, 15.0), 2)),
                    Evening_feeds=Decimal(round(random.uniform(5.0, 15.0), 2)),
                    Total_feeds=Decimal('0.0'), # Calculated in save
                    Comments='Generated by script'
                )
                
                # Calling save() is required to trigger total calculation overriding in model
                record.save()
                
    print(f"Successfully generated {Eggs_production.objects.count()} egg production records!")

if __name__ == "__main__":
    generate_data()
