# Generated by Django 5.0 on 2026-03-16 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_eggs_production'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_date', models.DateField(help_text='m/d/y')),
                ('Season_or_crop', models.CharField(help_text='e.g., Wheat 2026', max_length=50)),
                ('Seed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Fertilizer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Crop_sale', models.DecimalField(decimal_places=2, default=0, help_text='Income from crop sale', max_digits=12)),
                ('Total_investment', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('Profit', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FarmExpense',
            },
        ),
    ]
