# Generated by Django 5.0 on 2026-03-16 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_farmexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(help_text='Select crop type for water estimation', max_length=100)),
                ('field_area', models.DecimalField(decimal_places=2, help_text='Area in Acres', max_digits=8)),
                ('water_source_flow_rate', models.DecimalField(decimal_places=2, help_text='Pump flow rate in Liters per Minute (LPM)', max_digits=10)),
                ('calculated_time_minutes', models.IntegerField(default=0, editable=False)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WaterSchedule',
            },
        ),
    ]
