# Generated by Django 5.0 on 2026-03-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_waterschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterschedule',
            name='mobile_number',
            field=models.CharField(default='', help_text='Phone number to send SMS alert to (e.g. +919876543210)', max_length=15),
        ),
    ]
