# Generated by Django 5.0 on 2026-03-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_waterschedule_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterschedule',
            name='water_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Dry', 'Dry')], default='Dry', help_text='Current water level of the land', max_length=20),
        ),
    ]
