# Generated by Django 5.0 on 2026-03-17 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_waterschedule_water_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retail_Crop_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(help_text='m/d/y')),
                ('Crop_Name', models.CharField(max_length=50)),
                ('Quantity_Sold', models.DecimalField(decimal_places=2, help_text='Quantity in Kg/Tons', max_digits=10)),
                ('Unit_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_Amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Payment_Method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Other', 'Other')], max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Retail_Crop_Sales',
            },
        ),
        migrations.CreateModel(
            name='Retail_Egg_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(help_text='m/d/y')),
                ('Tray_Count', models.IntegerField(default=0, help_text='Number of trays sold')),
                ('Egg_Count', models.IntegerField(default=0, help_text='Number of individual eggs sold')),
                ('Price_Per_Tray', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Price_Per_Egg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Total_Amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Retail_Egg_Sales',
            },
        ),
        migrations.CreateModel(
            name='Retail_Machinery_Renting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(help_text='m/d/y')),
                ('Machinery_Used', models.CharField(max_length=100)),
                ('Service_Provided', models.CharField(max_length=100)),
                ('Hours_Rented', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Rate_Per_Hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_Amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Retail_Machinery_Renting',
            },
        ),
        migrations.CreateModel(
            name='Retail_Milk_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(help_text='m/d/y')),
                ('Quantity_Liters', models.DecimalField(decimal_places=2, help_text='Quantity in Liters', max_digits=10)),
                ('Price_Per_Liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_Amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Retail_Milk_Sales',
            },
        ),
    ]
