# Generated by Django 5.0 on 2026-03-20 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_retail_crop_sales_retail_egg_sales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retail_Livestock_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(help_text='m/d/y')),
                ('Animal_Type', models.CharField(max_length=50)),
                ('Breed', models.CharField(blank=True, max_length=50)),
                ('Quantity_Sold', models.IntegerField(default=1, help_text='Number of animals')),
                ('Unit_Price', models.DecimalField(decimal_places=2, help_text='Price per animal', max_digits=10)),
                ('Total_Amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Retail_Livestock_Sales',
            },
        ),
    ]
