# Generated by Django 5.0 on 2026-03-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_retail_livestock_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_egg_sales',
            name='Payment_Method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Other', 'Other')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='retail_livestock_sales',
            name='Payment_Method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Other', 'Other')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='retail_machinery_renting',
            name='Payment_Method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Other', 'Other')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='retail_milk_sales',
            name='Payment_Method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Other', 'Other')], default='Cash', max_length=20),
        ),
    ]
