# Generated by Django 5.0 on 2026-03-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_retail_egg_sales_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_expenses',
            name='Expense_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crop_expenses',
            name='Payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crop_expenses',
            name='Receipt_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crop_expenses',
            name='Supplier',
            field=models.CharField(max_length=255),
        ),
    ]
