# Generated by Django 5.0 on 2026-03-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_alter_crop_expenses_expense_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop_operations',
        ),
    ]
