# Generated by Django 5.0 on 2026-03-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_delete_crop_operations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop_expenses',
            name='Budget',
        ),
    ]
