# Generated by Django 5.0 on 2026-03-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_remove_crop_expenses_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_crop_sales',
            name='Product_Image',
            field=models.ImageField(blank=True, null=True, upload_to='retail_images/'),
        ),
        migrations.AddField(
            model_name='retail_egg_sales',
            name='Product_Image',
            field=models.ImageField(blank=True, null=True, upload_to='retail_images/'),
        ),
        migrations.AddField(
            model_name='retail_livestock_sales',
            name='Product_Image',
            field=models.ImageField(blank=True, null=True, upload_to='retail_images/'),
        ),
        migrations.AddField(
            model_name='retail_machinery_renting',
            name='Product_Image',
            field=models.ImageField(blank=True, null=True, upload_to='retail_images/'),
        ),
        migrations.AddField(
            model_name='retail_milk_sales',
            name='Product_Image',
            field=models.ImageField(blank=True, null=True, upload_to='retail_images/'),
        ),
    ]
