# Generated by Django 5.0 on 2026-03-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_retail_crop_sales_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+91 91594 42229', max_length=20)),
                ('email', models.EmailField(default='support@agrimarket.com', max_length=254)),
                ('address', models.TextField(default='#42, Madurai Bypass Rd, Madurai, TN 625020')),
            ],
            options={
                'verbose_name': 'Contact Detail',
                'verbose_name_plural': 'Contact Details',
            },
        ),
    ]
